'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FeaturedWorkers

    '''<summary>
    '''CategoryList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CategoryList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''blockedsect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blockedsect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divElectrician control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divElectrician As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PaintnDecoration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PaintnDecoration As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PoolSpel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PoolSpel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GardennLandscaping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GardennLandscaping As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Security control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Security As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''KitchenSpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KitchenSpec As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GeyserSpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeyserSpec As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PestCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PestCon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tilingspec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tilingspec As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''roofspec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents roofspec As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MRstore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MRstore As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''airCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents airCon As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divBlocked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBlocked As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
