'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class generateQuotation

    '''<summary>
    '''lblQuoteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuoteDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuoteDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQuoteHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuoteHours As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuoteHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteHours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQuoteAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuoteAmount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuoteAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuoteAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReg As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
