CREATE TABLE [dbo].[ClientRating](
	[Client] [varchar](50) NOT NULL,
	[JobID] [int] NOT NULL,
	[Rating] [int] NULL,
	[Comment] [varchar](max) NULL,
 CONSTRAINT [PK_ClientRating] PRIMARY KEY CLUSTERED 
(
	[Client] ASC,
	[JobID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]