CREATE TABLE [dbo].[AverageWorkerRating](
	[Worker] [varchar](50) NOT NULL,
	[AverageRating] [int] NULL,
 CONSTRAINT [PK_AverageWorkerRating] PRIMARY KEY CLUSTERED 
(
	[Worker] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]