CREATE TABLE [dbo].[AverageClientRating](
	[Client] [varchar](50) NOT NULL,
	[AverageRating] [int] NULL,
 CONSTRAINT [PK_AverageClientRating] PRIMARY KEY CLUSTERED 
(
	[Client] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
